package com.example.narutouniverse.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFFA23F00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBCC)
val md_theme_light_onPrimaryContainer = Color(0xFF351000)
val md_theme_light_secondary = Color(0xFF6A5F00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFBE408)
val md_theme_light_onSecondaryContainer = Color(0xFF201C00)
val md_theme_light_tertiary = Color(0xFF006493)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCAE6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E30)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1C00)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1C00)
val md_theme_light_surfaceVariant = Color(0xFFF4DED5)
val md_theme_light_onSurfaceVariant = Color(0xFF52443D)
val md_theme_light_outline = Color(0xFF85736C)
val md_theme_light_inverseOnSurface = Color(0xFFFFF48E)
val md_theme_light_inverseSurface = Color(0xFF363100)
val md_theme_light_inversePrimary = Color(0xFFFFB695)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFA23F00)
val md_theme_light_outlineVariant = Color(0xFFD8C2BA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB695)
val md_theme_dark_onPrimary = Color(0xFF571F00)
val md_theme_dark_primaryContainer = Color(0xFF7B2E00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBCC)
val md_theme_dark_secondary = Color(0xFFDDC800)
val md_theme_dark_onSecondary = Color(0xFF373100)
val md_theme_dark_secondaryContainer = Color(0xFF4F4700)
val md_theme_dark_onSecondaryContainer = Color(0xFFFBE408)
val md_theme_dark_tertiary = Color(0xFF8DCDFF)
val md_theme_dark_onTertiary = Color(0xFF00344F)
val md_theme_dark_tertiaryContainer = Color(0xFF004B70)
val md_theme_dark_onTertiaryContainer = Color(0xFFCAE6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1C00)
val md_theme_dark_onBackground = Color(0xFFF2E66A)
val md_theme_dark_surface = Color(0xFF1F1C00)
val md_theme_dark_onSurface = Color(0xFFF2E66A)
val md_theme_dark_surfaceVariant = Color(0xFF52443D)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BA)
val md_theme_dark_outline = Color(0xFFA08D85)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1C00)
val md_theme_dark_inverseSurface = Color(0xFFF2E66A)
val md_theme_dark_inversePrimary = Color(0xFFA23F00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB695)
val md_theme_dark_outlineVariant = Color(0xFF52443D)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFF6F1C)

